- name: variables
  hosts: localhost
  vars:
    Course: "Ansible"
    Trainer: "Sivakumar"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "we are learning {{Course}} from trainer {{trainer}}, duration is {{duration}}"